CREATE TABLE produto2 (
	ID SERIAL,	
	ID_NF INTEGER,
	ID_ITEM INTEGER,
	COD_PROD INTEGER,
	VALOR_UNIT NUMERIC,
	QUANTIDADE INTEGER,
	DESCONTO INTEGER,
	PRIMARY KEY (ID)
)


SELECT * FROM produto2

INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (5, 2, 1, 71.0, 4, NULL);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (6, 2, 2, 26.0, 18, 20);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (0, 3, 0, 23.0, 4, 5);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (3, 3, 1, 84.0, 22, 1);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (0, 1, 1, 57.0, 4, NULL);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (1, 2, 3, 11.0, 5, 5);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (0, 3, 1, 66.0, 20, 1);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (5, 1, 3, 90.0, 2, 1);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (3, 1, 3, 49.0, 23, 1);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (3, 2, 1, 33.0, 21, 4);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (6, 1, 3, 93.0, 16, 5);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (5, 3, 0, 7.0, 23, 15);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (0, 2, 3, 39.0, 6, 15);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (5, 1, 0, 51.0, 0, NULL);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (3, 1, 1, 97.0, 20, 5);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (1, 3, 1, 53.0, 2, 20);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (4, 2, 3, 66.0, 12, NULL);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (5, 2, 3, 56.0, 10, 5);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (5, 1, 0, 56.0, 23, NULL);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (3, 0, 0, 46.0, 5, 5);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (3, 0, 0, 76.0, 20, NULL);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (4, 1, 0, 39.0, 0, 4);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (4, 0, 1, 94.0, 9, 5);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (6, 3, 1, 39.0, 18, 1);
INSERT INTO produto2(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO) VALUES (1, 1, 0, 82.0, 21, 4);
SELECT * FROM produto2


SELECT 
	ID_NF, 
	ID_ITEM, 
	COD_PROD, 
	VALOR_UNIT,
	DESCONTO
FROM produto2 WHERE DESCONTO IS NOT NULL;


UPDATE produto2 SET DESCONTO = NULL WHERE DESCONTO = 0;
SELECT * FROM produto2


SELECT 
	id_nf, 
	id_item, 
	cod_prod, 
	valor_unit
FROM produto2 WHERE valor_unit > 10;


UPDATE produto2 SET valor_unit = 1000 WHERE id_item = 2;
SELECT * FROM produto2





